### ISSUE TITLE
Transférer la propriété de ce dépôt à l'organisation OpenFisca

### ISSUE THREAD

**Issue by guillett** [openfisca/extension-template#1]
Il semblerait que ce dépôt soit _superseeded_ par [openfisca/openfisca-extension-template](https://github.com/openfisca/openfisca-extension-template) mais il n'est pas possible d'ouvrir des _issues_ sur [openfisca/openfisca-extension-template](https://github.com/openfisca/openfisca-extension-template).

**Comment by MattiSG** [comment]
Oui, car c'est un fork. Bien vu. Le plus simple est probablement de réintégrer les modifs du fork ici puis de transférer la propriété à l'organisation `openfisca`.

**Comment by MattiSG** [comment]
Moved from `sgmap/openfisca-extension-template` to `openfisca/extension-template` with all changes included.

cc @openfisca/core-contributors
