### ISSUE TITLE
Fix continuous deployement

### ISSUE THREAD

**Issue by Anna-Livia** [openfisca/extension-template#12]
Since the hosting of the legislation explorer on /legislation (PR #550) the CD does not function properly :
ourput from [Circle CI](https://circleci.com/gh/openfisca/legislation-explorer/550)
```sh

> legislation-explorer@0.0.1 build /home/openfisca/legislation-explorer
> webpack --config ./webpack.config.prod.babel.js

Error: EACCES: permission denied, open '/home/openfisca/legislation-explorer/public/main-e3048d56dd2f23a90ac0.js'
    at Error (native)
```

**Comment by sandcha** [comment]
@Anna-Livia Issue to move to legislation explorer repository?

**Comment by Morendil** [comment]
The build is currently green; closing.
