### ISSUE TITLE
Add CI directly in package and bootstrap

### ISSUE THREAD

**Issue by guillett** [openfisca/extension-template#3]
Example in
- [openfisca-rennesmetropole](https://github.com/sgmap/openfisca-rennesmetropole/pull/1/commits/809c04756aa29e3575d08b96efb6b90e5fd3c53e)
- [openfisca-paris](https://github.com/sgmap/openfisca-paris/pull/9)

Parameters :
- `EXTENSION_NAME`
- `COUNTRY_NAME`
- `VERSION_REQUIREMENTS`

**Comment by Morendil** [comment]
I think this was fixed, as this repo has tests and is under CircleCI. Feel free to reopen if I'm misinterpreting.
