### ISSUE TITLE
Use `pre-commit` to apply style guide automatically and consistently across repositories

### ISSUE THREAD

**Issue by bonjourmauko** [openfisca/extension-template#39]
When I'm developing an extension or contributing to this repository,
I want style guide to be [enforced automatically and consistently](https://pre-commit.com/) across OpenFisca repositories,
so I can reduce my mental overhead and add value to users instead.

**Comment by MattiSG** [comment]
I interpret the 👍 emoji reaction to https://github.com/openfisca/openfisca-core/issues/1016#issuecomment-895232869 and the following closure of https://github.com/openfisca/openfisca-core/issues/1016 as an agreement that this is not considered anymore. Feel free to reopen if I misinterpreted! 🙂
